export default [
  {
    name: 'Card 3 columns',
    props: {
      width: 'sameWidth',
      card1: {
        icon: 'tv',
        theme: 'fire',
        heading: 'Donec posuere vulputate arcu',
        text: 'Lorem ipsum dolor sit amet, <a href="http://example.de">consetetur</a> elitr, sediam. Lorem ipsum dolor sit amet, con setetur sadipscing elitr, sed diam.',
        href: '/test',
        buttonText: 'Link to page',
        linkTile: false,
      },
      card2: {
        icon: 'tv',
        theme: 'sunny',
        heading: 'Donec posuere vulputate arcu',
        text: 'Lorem ipsum dolor sit amet, <a href="http://example.de">consetetur</a> elitr, sediam. Lorem ipsum dolor sit amet, con setetur sadipscing elitr, sed diam.',
        href: '/test',
        buttonText: 'Link to page',
        linkTile: false,
      },
      card3: {
        icon: 'tv',
        theme: 'misty',
        heading: 'Donec posuere vulputate arcu',
        text: 'Lorem ipsum dolor sit amet, <a href="http://example.de">consetetur</a> elitr, sediam. Lorem ipsum dolor sit amet, con setetur sadipscing elitr, sed diam.',
        href: '/test',
        buttonText: 'Link to page',
        linkTile: false,
      },
    },
  },
  {
    name: 'Card 3 columns (first tiles smaller)',
    props: {
      width: 'firstTilesSmaller',
      card1: {
        icon: 'tv',
        theme: 'aubergine',
        heading: 'Donec posuere vulputate arcu',
        text: 'Lorem ipsum dolor sit amet, consetetur elitr, sediam. Lorem ipsum dolor sit amet, con setetur sadipscing elitr, sed diam.',
        href: '/test',
        buttonText: 'Link to page',
        linkTile: true,
      },
      card2: {
        icon: 'tv',
        theme: 'aubergine',
        heading: 'Donec posuere vulputate arcu',
        text: 'Lorem ipsum dolor sit amet, consetetur elitr, sediam. Lorem ipsum dolor sit amet, con setetur sadipscing elitr, sed diam.',
        href: '/test',
        buttonText: 'Link to page',
      },
      card3: {
        icon: 'tv',
        theme: 'aubergine',
        heading: 'Donec posuere vulputate arcu',
        text: 'Lorem ipsum dolor sit amet, consetetur elitr, sediam. Lorem ipsum dolor sit amet, con setetur sadipscing elitr, sed diam.',
        href: '/test',
        buttonText: 'Link to page',
      },
    },
  },
  {
    name: 'Card 3 columns (last tile smaller)',
    props: {
      width: 'lastTilesSmaller',
      card1: {
        icon: 'tv',
        theme: 'aubergine',
        heading: 'Donec posuere vulputate arcu',
        text: 'Lorem ipsum dolor sit amet, consetetur elitr, sediam. Lorem ipsum dolor sit amet, con setetur sadipscing elitr, sed diam.',
        href: '/test',
        buttonText: 'Link to page',
        linkTile: true,
      },
      card2: {
        icon: 'tv',
        theme: 'aubergine',
        heading: 'Donec posuere vulputate arcu',
        text: 'Lorem ipsum dolor sit amet, consetetur elitr, sediam. Lorem ipsum dolor sit amet, con setetur sadipscing elitr, sed diam.',
        href: '/test',
        buttonText: 'Link to page',
      },
      card3: {
        icon: 'tv',
        theme: 'aubergine',
        heading: 'Donec posuere vulputate arcu',
        text: 'Lorem ipsum dolor sit amet, consetetur elitr, sediam. Lorem ipsum dolor sit amet, con setetur sadipscing elitr, sed diam.',
        href: '/test',
        buttonText: 'Link to page',
      },
    },
  },
]
